baseURL: 'https://note.thefoxhut.com/'
title: "A Fox's Notebook"
languageCode: 'en-us'
theme: "PaperMod"
enableRobotsTXT: false
enableInlineShortcodes: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: '/:title/'

menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Tags
      weight: 20
      identifier: tags
      url: /tags/

params:
  author: Fox
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: "Hi there"
    Content: >
        Welcome. This is a notebook, powered by Hugo and PaperMod theme.

taxonomies:
  category: categories
  tag: tags
  series: series
