baseURL = 'https://silvesterpang.github.io/'
languageCode = 'en-us'
title = "A Fox's Notes"
enableRobotsTXT = false
theme = "PaperMod"
#disqusShortname = "fox"

[permalinks]
  posts = "/:title/"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

[params]
  author = "Fox"
